import logging
import os
from datetime import date

from dotenv import load_dotenv

try:
    from resend import Resend
except Exception:
    Resend = None

# fallback import for HTTP send if resend lib is not available
import requests


logger = logging.getLogger(__name__)


def format_digest(jobs: list[dict]) -> str:
    """
    Format a list of scored jobs into a readable plain-text email body.
    
    Args:
        jobs: List of scored job dicts with keys: title, company, url, score, 
              skills_match_pct, missing_skills, seniority_fit, reason
    
    Returns:
        Plain-text email body as a string
    """
    if not jobs:
        return "No new job matches were found for you today."
    
    # Format header with date
    today = date.today().strftime("%B %d, %Y")
    body = f"=== Job Scout Digest — {today} ===\n{len(jobs)} jobs found for you today.\n\n"
    
    # Format each job
    for idx, job in enumerate(jobs, 1):
        title = job.get("title", "Unknown")
        company = job.get("company", "Unknown")
        score = job.get("score", 0.0)
        skills_match_pct = job.get("skills_match_pct", 0)
        seniority_fit = job.get("seniority_fit", "unknown")
        missing_skills = job.get("missing_skills", [])
        reason = job.get("reason", "No reason provided")
        url = job.get("url", "")
        
        # Format missing skills line
        if missing_skills:
            missing_str = ", ".join(missing_skills)
        else:
            missing_str = "none"
        
        # Build job entry
        job_entry = (
            f"[{idx}] {title} — {company}\n"
            f"Score: {score:.1f}/10 | Skills match: {skills_match_pct}% | Seniority: {seniority_fit}\n"
            f"Missing: {missing_str}\n"
            f"Why: {reason}\n"
        )
        
        if url:
            job_entry += f"Apply: {url}\n"
        
        body += job_entry + "\n"
    
    # Add footer
    body += "---\nGenerated by Job Scout. Good luck."
    
    return body


def send_digest(recipient_email: str, body: str, job_count: int) -> bool:
    """
    Send a digest email using the Resend API.
    
    Args:
        recipient_email: Recipient's email address
        body: Plain-text email body
        job_count: Number of jobs in the digest
    
    Returns:
        True if email sent successfully, False otherwise
    """
    # Load environment variables
    api_key = os.getenv("RESEND_API_KEY")
    sender_email = os.getenv("SENDER_EMAIL")
    
    # Validate required environment variables
    if not api_key:
        logger.error("RESEND_API_KEY not set in environment variables")
        return False
    
    if not sender_email:
        logger.error("SENDER_EMAIL not set in environment variables")
        return False
    
    # Try using the official resend library if available
    if Resend is not None:
        try:
            client = Resend(api_key=api_key)
            subject = f"Job Scout — {job_count} jobs for you today"
            response = client.emails.send(
                {
                    "from": sender_email,
                    "to": recipient_email,
                    "subject": subject,
                    "text": body,
                }
            )
            logger.info(f"Digest email sent to {recipient_email} (via resend lib)")
            return True
        except Exception as e:
            logger.error(f"Resend library send failed: {e}")
            # fall through to HTTP fallback

    # Fallback: call Resend API directly via requests with timeout
    try:
        api_url = "https://api.resend.com/emails"
        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        }
        payload = {
            "from": sender_email,
            "to": recipient_email,
            "subject": f"Job Scout — {job_count} jobs for you today",
            "text": body,
        }
        resp = requests.post(api_url, json=payload, headers=headers, timeout=15)
        if resp.status_code >= 200 and resp.status_code < 300:
            logger.info(f"Digest email sent to {recipient_email} (via HTTP fallback)")
            return True
        else:
            logger.error(
                f"Resend HTTP fallback failed: status={resp.status_code} body={resp.text}"
            )
            return False
    except Exception as e:
        logger.exception(f"Failed to send digest email via HTTP fallback: {e}")
        return False


if __name__ == "__main__":
    # Load environment variables
    load_dotenv()
    
    # Create 2 fake jobs for testing
    fake_jobs = [
        {
            "title": "Senior Backend Engineer",
            "company": "TechCorp",
            "url": "https://techcorp.com/jobs/senior-backend",
            "score": 8.5,
            "skills_match_pct": 85,
            "missing_skills": ["Docker", "Kubernetes"],
            "seniority_fit": "good fit",
            "reason": "Strong Python and FastAPI match; missing infra skills",
        },
        {
            "title": "Full Stack Developer",
            "company": "StartupXYZ",
            "url": "https://startupxyz.com/jobs/fullstack",
            "score": 7.2,
            "skills_match_pct": 72,
            "missing_skills": ["React"],
            "seniority_fit": "overqualified",
            "reason": "Good backend skills but frontend framework unknown",
        },
    ]
    
    # Format and print the digest
    digest_text = format_digest(fake_jobs)
    print(digest_text)
    print("\n" + "="*60)
    print("(Email would be sent with send_digest() — not called in test)")
